# This file was generated by the {rix} R package v0.17.4 on 2026-01-24
# with following call:
# >rix(date = c(latest,
#  > "2026-01-05",
#  > "2025-11-24",
#  > "2025-11-03",
#  > "2025-11-01")[3],
#  > r_pkgs = r_pkgs,
#  > system_pkgs = system_pkgs,
#  > git_pkgs = gh_pkgs,
#  > ide = c("positron",
#  > "rstudio")[1],
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = shell_hook,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2025-11-24.tar.gz") { config.allowUnfree = true; };
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      air
      arrow
      attachment
      autometric
      available
      bslib
      chromote
      cli
      covr
      crew
      dbplyr
      devtools
      dplyr
      DT
      duckdb
      furrr
      future
      future_apply
      gender
      gert
      ggdag
      ggdist
      ggplot2
      ggraph
      ggtext
      ggview
      gh
      gittargets
      here
      httptest
      httr
      igraph
      janitor
      jsonlite
      keyring
      knitr
      leaflet
      logger
      lubridate
      mcptools
      mirai
      munsell
      nanonext
      osmdata
      pins
      pkgdown
      plotly
      polite
      promises
      purrr
      Quandl
      quarto
      reticulate
      riingo
      rix
      rixpress
      rmarkdown
      rnaturalearth
      rvest
      sf
      shiny
      shinydashboard
      shinyjs
      shinylive
      spelling
      stringr
      styler
      tarchetypes
      targets
      testthat
      tibble
      tidyfinance
      tidymodels
      tidyquant
      tidyselect
      tidytuesdayR
      tidyverse
      treasury
      units
      usethis
      visNetwork
      WikidataQueryServiceR
      WikidataR
      withr;
  };
 
    btw = (pkgs.rPackages.buildRPackage {
      name = "btw";
      src = pkgs.fetchgit {
        url = "https://github.com/posit-dev/btw";
        rev = "78379217b2328dae8d5926dd3025593a34a92545";
        sha256 = "sha256-LBqqGto2hgvTbYaYculog4ifuJBUnXeUsTyUcM/jQnA=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          brio
          cli
          clipr
          dplyr
          ellmer
          fs
          jsonlite
          lifecycle
          mcptools
          pkgsearch
          rlang
          rmarkdown
          rstudioapi
          S7
          sessioninfo
          skimr
          tibble
          withr
          xml2;
      };
    });

    roxy.shinylive = (pkgs.rPackages.buildRPackage {
      name = "roxy.shinylive";
      src = pkgs.fetchgit {
        url = "https://github.com/insightsengineering/roxy.shinylive";
        rev = "c8a1967b0cb79a6bc6a0eab331bd80c57401d371";
        sha256 = "sha256-R5iJWQTyDt292bFBG0hQ5Om+N+QqRgLzZgezX1HrmTg=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) 
          glue
          jsonlite
          lzstring
          roxygen2
          stringr;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      awscli2
      bc
      btop
      cacert
      clang
      claude-code
      claude-monitor
      cmdstan
      curlMinimal
      direnv
      duckdb
      gcc
      gemini-cli
      gettext
      gh
      git
      glibcLocales
      gnupg
      htop
      jq
      less
      libgcc
      libiconv
      locale
      nano
      nix
      nodejs
      pandoc
      positron-bin
      quarto
      R
      texliveBasic
      toybox
      tree
      typst
      unzip
      which;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    #<- buildInputs = [ roxy.shinylive btw rpkgs system_packages ];
    buildInputs = [ roxy.shinylive btw ] ++ rpkgs ++ system_packages;
    shellHook = ''
    
# =============================================================================
# SHELL HOOK: Critical setup for Nix environment with Positron integration
# =============================================================================
#
# CRITICAL ESCAPING RULES - THIS HAS BROKEN MULTIPLE TIMES
#
# ⚠️ CRITICAL WARNING: NEVER USE QUOTE CHARACTERS IN DOCUMENTATION COMMENTS ⚠️
# The Nix parser interprets quotes EVEN IN COMMENTS as syntax elements!
# ❌ FORBIDDEN in documentation: Double quotes, single quotes, backticks
# ✅ ALLOWED in documentation: Use angle brackets <text> or plain descriptive text
# ℹ️ NOTE: Commented-out R code with quotes is OK (not passed to Nix parser)
# See: NIX_COMMENT_QUOTE_FIX.md for details on this recurring bug
#
# DETAILED DOCUMENTATION: See NIX_ESCAPING_RULES.md in this directory
#
# This R raw string becomes a Nix shellHook string in default.nix.
# The Nix shellHook uses DOUBLE QUOTES <shellHook = ...>, NOT single quotes.
#
# ESCAPING RULES:
# 1. In this R raw string: Use $HOME directly (no backslash).
# 2. In default.nix: Keep $HOME unescaped and unquoted in paths.
# 3. Avoid backslash-dollar because it creates a literal $HOME at runtime.
#
# CORRECT (in R raw string): mkdir -p $HOME/.config/positron
# GENERATES (in default.nix): mkdir -p $HOME/.config/positron
# IN NIX SHELL (runtime): mkdir -p /Users/username/.config/positron
#
# WRONG: mkdir -p with escaped dollar or quoted escaped dollar path
# → Generates: mkdir -p with literal $HOME or invalid Nix syntax
# → Result: literal $HOME directory or parse failure
#
# WHY: Backslash-dollar blocks shell expansion. Use plain $HOME instead.
#
# HISTORICAL ISSUES FIXED:
# 1. sed command trying to read R_LIBS_USER from non-existent path
# - Problem: $NIX_SHELL_PATH points to shell script, not directory
# - Solution: Removed sed command entirely, R_LIBS_USER set by Nix
# - Lines removed by post-processing in this file (search for Fix 3)
#
# 2. .nix-session.log file creation failing
# - Problem: touch \\$HOME/.nix-session.log had double backslash
# - When eval'd by default.sh, \\$ becomes \$ which doesn't expand
# - Solution: Removed these lines entirely as they're not critical
#
# 3. Arrow keys not working in interactive shell
# - Problem: Readline config created but user's shell (zsh) ignored it
# - Solution: default.sh detects user's actual shell and applies appropriate config
# - See default.sh lines 94-95 and 231-247 for implementation
#
# 4. ⚠️ CRITICAL: Nix syntax error unexpected invalid token (2025-11-28)
# - Problem: Comments containing quote characters cause Nix parse errors
# - In default.nix comments with quotes like <shellHook = <...>> break parser
# - Nix parser interprets quotes in comments as syntax elements
# - Solution: Replace all quotes in comments with angle brackets < >
# - Applies to ALL comments - avoid single quotes, double quotes, backticks
# - This bug has recurred multiple times - DO NOT add quotes back to comments!
# =============================================================================

# 1. Create the temporary wrapper script in a stable location
# Use inline expansion to avoid creating literal $WRAPPER_* files
# NOTE: Avoid using empty string pattern in case (breaks Nix multi-line strings)
valid_home=1
if [ -z "$HOME" ]; then
  valid_home=0
fi
case "$HOME" in
  *'$'*) valid_home=0 ;;
  /*) ;;
  *) valid_home=0 ;;
esac

user_ok=0
if [ -z "$USER" ]; then
  user_ok=0
else
  case "$USER" in
    *'$'*) user_ok=0 ;;
    *) if [ -d /Users/$USER ]; then user_ok=1; fi ;;
  esac
fi

if [ $valid_home -ne 1 ] && [ $user_ok -eq 1 ]; then
  HOME=/Users/$USER
  export HOME
  valid_home=1
fi

if [ $valid_home -ne 1 ]; then
  printf '%s\n' 'Skipping Positron wrapper setup due to invalid HOME.'
else
  mkdir -p $HOME/.config/positron

# The derivation output path from nix-build is stored at the GC root symlink.
# We read the absolute path of the built environment from this symlink.
NIX_SHELL_PATH=$(readlink /Users/johngavin/docs_gh/rix.setup/nix-shell-root)
if [ -z \"$NIX_SHELL_PATH\" ]; then
    # Fallback to current $out if the symlink is missing (though it should not be here)
    NIX_SHELL_PATH=\"$out\" 
fi

cat > $HOME/.config/positron/nix-terminal-wrapper.sh <<EOF
#!/bin/bash

printf '%s\n' 'Activating Nix shell environment...'

# 1. Source the Nix profile script from the *built derivation*.
# The path variable has been substituted here by the outer shell, so this line is a clean source command
# This command is the CRITICAL step that sets PATH, man pages, and other environment variables.
# This is also a shell command, equivalent to the source builtin
# Recommended fix for default.R (line ~204)
# This command is the CRITICAL step that sets PATH, man pages, and other environment variables.
true && source $NIX_SHELL_PATH/etc/profile.d/nix-shell.sh

# 2. Run environment activation hooks (if defined by Nix)
if declare -f __start_nix_shell_environment > /dev/null; then
    __start_nix_shell_environment
fi

# 3. Fix R Console Libraries: Ensure R finds the Nix-built packages.
# The R_LIB_PATH variable must still be escaped to prevent outer shell expansion here.
# DISABLED: This path doesn't exist - NIX_SHELL_PATH is the shell script, not a directory
# R_LIBS_USER should already be set by the Nix environment

# 4. Final confirmation before launch
printf '%s\n' 'Nix environment fully sourced.'

# 5. Ensure readline is configured for history navigation
# Create a temporary .bashrc for this session with readline settings
echo '# Nix shell readline configuration' > ~/.nix-shell-bashrc
echo 'set -o emacs' >> ~/.nix-shell-bashrc
echo 'bind \"\\e[A\": history-search-backward\"' >> ~/.nix-shell-bashrc
echo 'bind \"\\e[B\": history-search-forward\"' >> ~/.nix-shell-bashrc
echo 'bind \"\\e[C\": forward-char\"' >> ~/.nix-shell-bashrc
echo 'bind \"\\e[D\": backward-char\"' >> ~/.nix-shell-bashrc
echo >> ~/.nix-shell-bashrc
echo '# Source user bashrc if it exists' >> ~/.nix-shell-bashrc
echo 'if [ -f ~/.bashrc ]; then source ~/.bashrc; fi' >> ~/.nix-shell-bashrc

# 6. Launch the interactive shell with custom bashrc
# exec replaces the current process with the new shell, making it the final terminal session.
exec /usr/bin/env bash --rcfile ~/.nix-shell-bashrc -i

EOF

# 2. Make the script executable and export path for RStudio/Positron
chmod +x $HOME/.config/positron/nix-terminal-wrapper.sh
export RSTUDIO_TERM_EXEC=$HOME/.config/positron/nix-terminal-wrapper.sh
fi

# 3. Disable user Makevars to prevent Homebrew path conflicts
# User's ~/.R/Makevars may contain Homebrew-specific paths (e.g., /opt/homebrew/opt/libomp)
# These conflict with Nix-provided libraries. Setting R_MAKEVARS_USER to /dev/null
# disables user Makevars, ensuring R uses only Nix environment for compilation.
export R_MAKEVARS_USER=/dev/null

# IMPORTANT: Removed logic to modify ~/.zshrc or ~/.bashrc to prevent infinite recursion.

# === Other standard Nix shell setup ===
export PATH=/Users/johngavin/docs_gh/llm/bin:$PATH
unset CI
printf '%s\\n' 'Setup complete'
printf 'Terminal wrapper: %s\\n' $RSTUDIO_TERM_EXEC
printf 'RSTUDIO_TERM_EXEC set to execute new shell with Nix environment.\\n'

  '';
  }; 
in
  {
    inherit pkgs shell;
  }
