#!/usr/bin/env bash
# tests/test_email_cron_single_source_creds.sh
#
# llm#949: the cron email wrappers must get GMAIL_* from the SINGLE source
# (process environment injected by with-secrets/bws, else ~/.config/secrets.env)
# and FAIL CLOSED when it is absent -- never from per-job ~/.claude/env/*.env
# files, never by "relying on existing environment".
#
# Part A exercises .claude/scripts/lib/load_email_creds.sh directly.
# Part B runs a copy of each REAL wrapper inside a fake repo + fake HOME and
# proves (1) absent credentials -> ABORT, exit 1, before any nix/R/SMTP work;
# (2) credentials in the fixture secrets.env -> loaded (and a planted per-job
# env file with a DIFFERENT value is ignored). No wrapper ever reaches nix-shell
# or sends mail: the fake repo has no default.nix, so each one exits at its
# "nix file not found" guard, which is how "credentials accepted" is told apart
# from "credentials rejected" (the ABORT log line).
#
# Falsification hook: TEST_LIB_SRC=<path> substitutes another copy of the
# library (used to prove the suite goes red when fail-closed is removed).
#
# Exits 0 if all pass, 1 otherwise.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
LIB_SRC="${TEST_LIB_SRC:-${REPO_ROOT}/.claude/scripts/lib/load_email_creds.sh}"

PASS=0
FAIL=0
TMPDIR_ROOT="$(mktemp -d /tmp/test_email_single_source_XXXXXX)"
trap 'rm -rf "${TMPDIR_ROOT}"' EXIT

pass() { echo "PASS: $1"; PASS=$((PASS + 1)); }
fail() { echo "FAIL: $1 -- ${2:-}"; FAIL=$((FAIL + 1)); }

# Canary values: obviously fake, distinct per source so a wrong-source read is visible.
SECRET_PW="canary-single-source-pw-7781"
LEGACY_PW="canary-LEGACY-perjob-pw-0042"
SRC_USER="user-single@example.invalid"

# ── Part A: library ─────────────────────────────────────────────────────────
mkdir -p "${TMPDIR_ROOT}/a"
cat > "${TMPDIR_ROOT}/a/secrets.env" <<EOF
# GENERATED by secrets_cache_regen.sh from Bitwarden Secrets Manager
export OPENAI_API_KEY=canary-unrelated-key-1
GMAIL_USERNAME=${SRC_USER}
GMAIL_APP_PASSWORD="${SECRET_PW}"
REPORT_RECIPIENT='rcpt@example.invalid'
EOF

# run_lib ENVSPEC... -- runs `snippet` in a clean env with the library sourced.
run_lib() {
  local snippet="$1"; shift
  env -i PATH=/usr/bin:/bin HOME="${TMPDIR_ROOT}/a" "$@" \
    bash -c "set -uo pipefail; source '${LIB_SRC}'; log(){ echo \"LOG: \$1\"; }; ${snippet}" 2>&1
}

out="$(run_lib 'load_email_credentials log; echo "rc=$? U=$GMAIL_USERNAME P=$GMAIL_APP_PASSWORD R=$REPORT_RECIPIENT K=${OPENAI_API_KEY:-unset}"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/secrets.env")"
case "${out}" in
  *"rc=0 U=${SRC_USER} P=${SECRET_PW} R=rcpt@example.invalid K=unset"*)
    pass "A1 loads GMAIL_*/REPORT_RECIPIENT from secrets.env (quotes stripped), and ONLY those keys" ;;
  *) fail "A1 loads from secrets.env" "${out}" ;;
esac

out="$(run_lib 'load_email_credentials log; echo "rc=$? P=$GMAIL_APP_PASSWORD"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/secrets.env" GMAIL_USERNAME=injected GMAIL_APP_PASSWORD=injected-pw)"
case "${out}" in
  *"rc=0 P=injected-pw"*"with-secrets"*|*"with-secrets"*"rc=0 P=injected-pw"*)
    pass "A2 environment injection wins; secrets.env not consulted" ;;
  *) fail "A2 env injection wins" "${out}" ;;
esac

out="$(run_lib 'load_email_credentials log; echo "rc=$?"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/does-not-exist.env")"
case "${out}" in
  *"rc=1"*) pass "A3 absent secrets.env + empty env -> returns 1 (fail closed)" ;;
  *) fail "A3 fail closed on absent source" "${out}" ;;
esac

printf 'GMAIL_USERNAME=only-user@example.invalid\n' > "${TMPDIR_ROOT}/a/partial.env"
out="$(run_lib 'load_email_credentials log; echo "rc=$?"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/partial.env")"
case "${out}" in
  *"rc=1"*"GMAIL_APP_PASSWORD"*|*"GMAIL_APP_PASSWORD"*"rc=1"*) pass "A4 password missing -> returns 1 and names it" ;;
  *) fail "A4 missing password" "${out}" ;;
esac

out="$(run_lib 'email_credentials_gate log; echo "rc=$?"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/does-not-exist.env")"
case "${out}" in
  *"ABORT"*"rc=1"*) pass "A5 gate aborts (rc=1) with no credentials and no dry-run" ;;
  *) fail "A5 gate aborts" "${out}" ;;
esac

out="$(run_lib 'email_credentials_gate log; echo "rc=$?"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/does-not-exist.env" EMAIL_DRY_RUN=1)"
case "${out}" in
  *"WARN"*"dry run"*"rc=0"*) pass "A6 gate proceeds only under dry-run, loudly (WARN)" ;;
  *) fail "A6 gate dry-run" "${out}" ;;
esac

out="$(run_lib 'load_email_credentials log; echo "rc=$?"' SECRETS_ENV_FILE="${TMPDIR_ROOT}/a/secrets.env")"
case "${out}" in
  *"${SECRET_PW}"*) fail "A7 library never prints the secret value" "value leaked into output" ;;
  *) pass "A7 library never prints the secret value" ;;
esac

# ── Part B: real wrappers, fake repo + fake HOME ───────────────────────────
# wrapper  ->  log file name it writes under $HOME/.claude/logs, and how it reads
#              missing creds: abort | dryrun (weekly rollup degrades to dry run)
WRAPPERS=(
  "kb_digest_daily_cron.sh:kb_digest.log:abort"
  "roborev_daily_cron.sh:roborev_daily_email.log:abort"
  "config_digest_cron.sh:config_digest_email.log:abort"
  "overnight_self_review_email_cron.sh:overnight_self_review_email_launchd.log:abort"
  "roborev_weekly_rollup_cron.sh:roborev_weekly_rollup.log:dryrun"
)

# make_fake TAG -> echoes fake HOME; layout: $HOME/repo/{bin,.claude/scripts/lib}
make_fake() {
  local h="${TMPDIR_ROOT}/b_$1"
  mkdir -p "${h}/.claude/logs" "${h}/.claude/env" "${h}/.config" \
           "${h}/repo/bin" "${h}/repo/.claude/scripts/lib"
  cp "${LIB_SRC}" "${h}/repo/.claude/scripts/lib/load_email_creds.sh"
  # cron_deploy_pull is irrelevant here (no network, no git mutation): no-op stub.
  printf 'cron_deploy_pull() { return 0; }\n' > "${h}/repo/.claude/scripts/cron_deploy_pull.sh"
  printf 'wait_for_resolvable_host() { return 0; }\n' > "${h}/repo/.claude/scripts/wait_for_resolvable_host.sh"
  echo "${h}"
}

run_wrapper() {  # run_wrapper HOME WRAPPER [extra env...]
  local h="$1" w="$2"; shift 2
  cp "${REPO_ROOT}/bin/${w}" "${h}/repo/bin/${w}"
  env -i PATH=/usr/bin:/bin HOME="${h}" "$@" bash "${h}/repo/bin/${w}" > "${h}/stdout.log" 2>&1
  echo $?
}

for spec in "${WRAPPERS[@]}"; do
  w="${spec%%:*}"; rest="${spec#*:}"; logname="${rest%%:*}"; mode="${rest##*:}"

  if bash -n "${REPO_ROOT}/bin/${w}" 2>/dev/null; then pass "B ${w}: bash -n"; else fail "B ${w}: bash -n"; fi

  # B1: no credentials anywhere -> fail closed (or forced dry run for the weekly job)
  h="$(make_fake "${w}_none")"
  # A per-job env file with creds must be IGNORED (single source only).
  printf 'GMAIL_USERNAME=legacy@example.invalid\nGMAIL_APP_PASSWORD=%s\n' "${LEGACY_PW}" > "${h}/.claude/env/roborev_email.env"
  cp "${h}/.claude/env/roborev_email.env" "${h}/.claude/env/kb_digest.env"
  cp "${h}/.claude/env/roborev_email.env" "${h}/.claude/env/overnight_self_review.env"
  rc="$(run_wrapper "${h}" "${w}")"
  log="$(cat "${h}/.claude/logs/${logname}" 2>/dev/null)"
  if [ "${mode}" = "abort" ]; then
    if [ "${rc}" = "1" ] && printf '%s' "${log}" | grep -q "ABORT" && ! printf '%s' "${log}" | grep -q "nix file not found"; then
      pass "B1 ${w}: no single-source creds -> ABORT exit 1 before any nix/R/SMTP work"
    else
      fail "B1 ${w}: fail closed" "rc=${rc} log=${log}"
    fi
  else
    if printf '%s' "${log}" | grep -q "EMAIL_DRY_RUN forced to 1"; then
      pass "B1 ${w}: no single-source creds -> loud forced EMAIL_DRY_RUN=1"
    else
      fail "B1 ${w}: forced dry run" "rc=${rc} log=${log}"
    fi
  fi
  if printf '%s%s' "${log}" "$(cat "${h}/stdout.log" 2>/dev/null)" | grep -q "${LEGACY_PW}"; then
    fail "B1 ${w}: per-job env file ignored" "legacy canary value appeared in output"
  elif printf '%s' "${log}" | grep -q "Loading env from\|claude/env"; then
    fail "B1 ${w}: per-job env file ignored" "log references a per-job env file: ${log}"
  else
    pass "B1 ${w}: planted per-job ~/.claude/env/*.env is ignored"
  fi

  # B2: credentials in the fixture single source -> accepted (no ABORT), never echoed
  h="$(make_fake "${w}_ok")"
  printf 'GMAIL_USERNAME=%s\nGMAIL_APP_PASSWORD=%s\nREPORT_RECIPIENT=r@example.invalid\n' "${SRC_USER}" "${SECRET_PW}" > "${h}/.config/secrets.env"
  rc="$(run_wrapper "${h}" "${w}")"
  log="$(cat "${h}/.claude/logs/${logname}" 2>/dev/null)"
  if printf '%s' "${log}" | grep -q "Credentials read from single source" \
     && ! printf '%s' "${log}" | grep -q "ABORT\|forced to 1" \
     && ! printf '%s%s' "${log}" "$(cat "${h}/stdout.log" 2>/dev/null)" | grep -q "${SECRET_PW}"; then
    pass "B2 ${w}: creds from ~/.config/secrets.env accepted, value never logged"
  else
    fail "B2 ${w}: loads from single source" "rc=${rc} log=${log}"
  fi
done

echo ""
echo "Results: ${PASS} passed, ${FAIL} failed"
[ "${FAIL}" -eq 0 ]
