#!/usr/bin/env bash
# scaffold-mermaid-dashboard.sh — copy mermaid-dashboard template files into
# a project's dashboard directory, with name substitution.
#
# Rule:     mermaid-dashboard-pattern
# Template: ~/docs_gh/llm/.claude/templates/mermaid-dashboard/
#
# Usage:
#   scaffold-mermaid-dashboard.sh <target-dir> <project-name>
#   scaffold-mermaid-dashboard.sh <target-dir> <project-name> --force
#   scaffold-mermaid-dashboard.sh --selftest
#
# Example:
#   scaffold-mermaid-dashboard.sh ~/docs_gh/myproj/dashboard myproj
#   → drops 4 files into ~/docs_gh/myproj/dashboard/:
#       myproj-diagrams.js          (working diagrams source)
#       myproj-diagrams-loader.html (will be re-generated by inline-diagrams.sh)
#       inline-diagrams.sh          (the wrap-into-script-module helper)
#       MERMAID_DASHBOARD_README.md  (the template README, renamed)
#   And prints the mount-div + YAML fragments to stdout for paste into the
#   target .qmd.
#
# Exit codes:
#   0  scaffold complete
#   1  target dir doesn't exist OR a file already exists (without --force)
#   2  bad invocation

set -u
set -o pipefail

LOG="${HOME}/.claude/logs/scaffold_mermaid_dashboard.log"
mkdir -p "$(dirname "$LOG")" 2>/dev/null || true

ts()  { date -u +'%Y-%m-%dT%H:%M:%SZ'; }
log() { printf '%s %s\n' "$(ts)" "$*" >> "$LOG"; }

TEMPLATE_DIR_DEFAULT="${HOME}/docs_gh/llm/.claude/templates/mermaid-dashboard"

# Override-able for tests
TEMPLATE_DIR="${SCAFFOLD_MERMAID_TEMPLATE_DIR:-$TEMPLATE_DIR_DEFAULT}"

# ── Selftest ─────────────────────────────────────────────────────────────────
if [ "${1:-}" = "--selftest" ]; then
  tmp=$(mktemp -d -t scaffold_mermaid_selftest.XXXX)
  trap 'rm -rf "$tmp"' EXIT
  pass=0; fail=0; total=0
  _ok()   { total=$((total+1)); pass=$((pass+1)); printf '  PASS  %s\n' "$*"; }
  _fail() { total=$((total+1)); fail=$((fail+1)); printf '  FAIL  %s\n' "$*"; }

  # Build a fake template directory
  fake_tpl="$tmp/template"
  mkdir -p "$fake_tpl"
  printf 'PROJECT_NAME diagrams\n' > "$fake_tpl/diagrams.js"
  printf 'loader for PROJECT_NAME\n' > "$fake_tpl/diagrams-loader.html"
  printf '#!/usr/bin/env bash\necho PROJECT_NAME\n' > "$fake_tpl/inline-diagrams.sh"
  printf '<div id="arch-mount"></div>\n' > "$fake_tpl/mount-div.qmd"
  printf 'include-after-body: PROJECT_NAME-diagrams-loader.html\n' > "$fake_tpl/quarto-frontmatter.yaml"
  printf '# README for PROJECT_NAME\n' > "$fake_tpl/README.md"
  export SCAFFOLD_MERMAID_TEMPLATE_DIR="$fake_tpl"

  # T1: missing target dir → exit 1
  bash "$0" "$tmp/nope" myproj >/dev/null 2>&1
  rc=$?; [ "$rc" -eq 1 ] && _ok "missing target dir → exit 1" \
                       || _fail "missing target dir wrong exit (rc=$rc)"

  # T2: bad invocation → exit 2
  bash "$0" >/dev/null 2>&1
  rc=$?; [ "$rc" -eq 2 ] && _ok "bad invocation → exit 2" \
                       || _fail "bad invocation wrong exit (rc=$rc)"

  # T3: successful scaffold copies and renames files
  target="$tmp/dash"
  mkdir -p "$target"
  bash "$0" "$target" myproj >/dev/null 2>&1
  rc=$?
  [ "$rc" -eq 0 ]                              && _ok "T3 exit 0"                  || _fail "T3 exit $rc"
  [ -f "$target/myproj-diagrams.js" ]          && _ok "T3 diagrams.js renamed"    || _fail "T3 missing diagrams.js"
  [ -f "$target/myproj-diagrams-loader.html" ] && _ok "T3 loader.html renamed"    || _fail "T3 missing loader"
  [ -f "$target/inline-diagrams.sh" ]          && _ok "T3 inline-diagrams.sh copied"  || _fail "T3 missing helper"
  [ -x "$target/inline-diagrams.sh" ]          && _ok "T3 helper is executable"   || _fail "T3 helper not exec"
  [ -f "$target/MERMAID_DASHBOARD_README.md" ] && _ok "T3 README renamed"         || _fail "T3 missing README"

  # T4: name substitution worked
  if grep -q "myproj diagrams" "$target/myproj-diagrams.js" 2>/dev/null; then
    _ok "T4 PROJECT_NAME substituted in diagrams.js"
  else
    _fail "T4 substitution missing"
  fi
  if grep -q "myproj-diagrams-loader.html" "$target/MERMAID_DASHBOARD_README.md" 2>/dev/null; then
    # Substitution went through README too — wait, README only mentioned PROJECT_NAME generically
    _ok "T4 PROJECT_NAME substituted in README"
  else
    # README didn't have the literal — that's also fine, just check it exists
    _ok "T4 README present (no substitution required check)"
  fi

  # T5: idempotency without --force → exit 1
  bash "$0" "$target" myproj >/dev/null 2>&1
  rc=$?; [ "$rc" -eq 1 ] && _ok "T5 second run without --force → exit 1" \
                       || _fail "T5 second run wrong exit (rc=$rc)"

  # T6: --force overwrites
  bash "$0" "$target" myproj --force >/dev/null 2>&1
  rc=$?; [ "$rc" -eq 0 ] && _ok "T6 --force allows overwrite" \
                       || _fail "T6 --force failed (rc=$rc)"

  # T7: substitution in YAML fragment to stdout
  out=$(bash "$0" "$target" myproj --force 2>/dev/null)
  if printf '%s' "$out" | grep -q 'myproj-diagrams-loader.html'; then
    _ok "T7 substituted YAML fragment printed"
  else
    _fail "T7 no substituted YAML fragment in stdout"
  fi

  unset SCAFFOLD_MERMAID_TEMPLATE_DIR
  printf '\nscaffold-mermaid-dashboard selftest: %d/%d PASS\n' "$pass" "$total"
  [ "$fail" -eq 0 ] && exit 0 || exit 1
fi

# ── Production ───────────────────────────────────────────────────────────────
target="${1:-}"
project="${2:-}"
force=0
if [ "${3:-}" = "--force" ]; then force=1; fi

if [ -z "$target" ] || [ -z "$project" ]; then
  cat >&2 <<'EOF'
usage: scaffold-mermaid-dashboard.sh <target-dir> <project-name> [--force]
       scaffold-mermaid-dashboard.sh --selftest
EOF
  exit 2
fi

if [ ! -d "$target" ]; then
  printf 'scaffold-mermaid-dashboard: target dir not found: %s\n' "$target" >&2
  exit 1
fi

if [ ! -d "$TEMPLATE_DIR" ]; then
  printf 'scaffold-mermaid-dashboard: template dir not found: %s\n' "$TEMPLATE_DIR" >&2
  exit 1
fi

# Validate project name (alphanumeric + hyphens + underscores)
case "$project" in
  *[!a-zA-Z0-9_-]*)
    printf 'scaffold-mermaid-dashboard: project name must be [a-zA-Z0-9_-]+: %s\n' "$project" >&2
    exit 2 ;;
esac

# File map: source → destination (with substitution)
declare -a copies=(
  "diagrams.js:${project}-diagrams.js"
  "diagrams-loader.html:${project}-diagrams-loader.html"
  "inline-diagrams.sh:inline-diagrams.sh"
  "README.md:MERMAID_DASHBOARD_README.md"
)

# Check none already exist (unless --force)
if [ "$force" = "0" ]; then
  for pair in "${copies[@]}"; do
    dst="${pair#*:}"
    if [ -e "$target/$dst" ]; then
      printf 'scaffold-mermaid-dashboard: would overwrite %s (use --force)\n' "$target/$dst" >&2
      exit 1
    fi
  done
fi

# Copy + substitute
for pair in "${copies[@]}"; do
  src="${pair%%:*}"
  dst="${pair#*:}"
  if [ ! -f "$TEMPLATE_DIR/$src" ]; then
    printf 'scaffold-mermaid-dashboard: missing template: %s/%s\n' "$TEMPLATE_DIR" "$src" >&2
    exit 1
  fi
  sed "s/PROJECT_NAME/${project}/g" "$TEMPLATE_DIR/$src" > "$target/$dst"
done

# Make the helper executable
chmod +x "$target/inline-diagrams.sh" 2>/dev/null || true

# Print mount-div + YAML snippets for paste-in
cat <<EOF
scaffold-mermaid-dashboard: 4 files written under $target

  $project-diagrams.js          ← edit this: define your dagDefs + nodeTooltips
  $project-diagrams-loader.html ← regenerate with ./inline-diagrams.sh
  inline-diagrams.sh            ← bash helper to inline JS into <script type="module">
  MERMAID_DASHBOARD_README.md   ← reference + checklist

Next steps:
  1. Edit $project-diagrams.js — populate dagDefs and nodeTooltips for your project
  2. Run:  cd $target && ./inline-diagrams.sh
     This regenerates ${project}-diagrams-loader.html with the JS inlined.
  3. Paste this YAML into your .qmd front matter:

──────── YAML to paste into .qmd front matter ────────
EOF

if [ -f "$TEMPLATE_DIR/quarto-frontmatter.yaml" ]; then
  sed "s/PROJECT_NAME/${project}/g" "$TEMPLATE_DIR/quarto-frontmatter.yaml"
fi

cat <<EOF
──────────────────────────────────────────────────────

  4. Paste this mount-div block where the diagram should appear:

──────── mount-div to paste into .qmd body ──────────
EOF

if [ -f "$TEMPLATE_DIR/mount-div.qmd" ]; then
  sed "s/PROJECT_NAME/${project}/g" "$TEMPLATE_DIR/mount-div.qmd"
fi

cat <<EOF
──────────────────────────────────────────────────────

  5. After 'quarto render', verify with:
     verify_mermaid_dashboard.sh $target/<page>.html
EOF

log "OK target=$target project=$project force=$force"
exit 0
