# This file was generated by the {rix} R package v0.18.1 on 2026-06-30
# with following call:
# >rix(date = "2026-02-02",
#  > r_pkgs = r_pkgs,
#  > git_pkgs = git_pkgs,
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > shell_hook = "export R_MAKEVARS_USER=/dev/null",
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
#
# MANUAL PATCHES (applied after rix generation):
#   1. buildInputs: changed from [ muttest rpkgs system_packages ] to
#      [ muttest ] ++ rpkgs ++ system_packages (fixes nested list issue)
#   2. muttest derivation: added doCheck = false (test suite needs Suggests
#      not in this minimal env: usethis, covr, cucumber, purrr, stringr)
#   3. digest: added to rpkgs (undeclared dep in muttest DESCRIPTION,
#      required by PackageCopyStrategy)
#   4. usethis: added to rpkgs (required by nix fixupPhase namespace chain)
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-02-02.tar.gz") {};

  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages)
      checkmate
      cli
      digest
      fs
      mirai
      R6
      rlang
      testthat
      treesitter
      treesitter_r
      usethis
      withr;
  };

    muttest = (pkgs.rPackages.buildRPackage {
      name = "muttest";
      src = pkgs.fetchgit {
        url = "https://github.com/jakubsob/muttest";
        rev = "6cec45271f67b155175c18a663c339af86db5942";
        sha256 = "sha256-HZMtYkaBlyNRwc6vry432Ljm5jneuHDi0XApXrw5q3w=";
      };
      # Skip test suite: muttest Suggests (usethis, covr, cucumber, purrr, stringr)
      # are not in this minimal environment. The package installs and loads correctly.
      doCheck = false;
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages)
          checkmate
          cli
          digest
          fs
          mirai
          R6
          rlang
          testthat
          treesitter
          treesitter_r
          usethis
          withr;
      };
    });

  system_packages = builtins.attrValues {
    inherit (pkgs)
      glibcLocales
      nix
      R;
  };

  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [ muttest ] ++ rpkgs ++ system_packages;
    shellHook = ''
    export R_MAKEVARS_USER=/dev/null
  '';
  };
in
  {
    inherit pkgs shell;
  }
