# This file was generated by the {rix} R package v0.18.1 on 2026-06-30
# with following call:
# >rix(date = "2026-02-02",
#  > r_pkgs = c("profvis"),
#  > system_pkgs = c("git"),
#  > git_pkgs = list(list(package_name = "debrief",
#  > repo_url = "https://github.com/r-lib/debrief",
#  > commit = "ce2a45e3a5e8d6e609fbb43ce8233ff4996acfab")),
#  > ide = "none",
#  > project_path = ".",
#  > overwrite = TRUE,
#  > r_ver = "4.5.2")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides improved
# compatibility with older R versions and R packages for Linux/WSL and
# Apple Silicon computers.
# Report any issues to https://github.com/ropensci/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/2026-02-02.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      profvis;
  };
 
    debrief = (pkgs.rPackages.buildRPackage {
      name = "debrief";
      src = pkgs.fetchgit {
        url = "https://github.com/r-lib/debrief";
        rev = "ce2a45e3a5e8d6e609fbb43ce8233ff4996acfab";
        sha256 = "sha256-ewWXV6nRBFKwTTF1DCsyhlJzm3yT3nbZJjgAtnJtr+M=";
      };
      propagatedBuildInputs = builtins.attrValues {
        inherit (pkgs.rPackages) ;
      };
    });
      
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      git
      glibcLocales
      nix
      R;
  };
  
  shell = pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.stdenv.hostPlatform.system == "x86_64-linux" then "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    
    buildInputs = [ debrief ] ++ rpkgs ++ system_packages;
    
  }; 
in
  {
    inherit pkgs shell;
  }
