#!/usr/bin/env bash
# inline-diagrams.sh — wrap diagrams.js into a <script type="module"> block
# so it loads correctly from `file://` URLs (Chrome blocks
# <script type="module" src="local.js"> from file:// origins, but inline
# modules work). Run after every edit to diagrams.js.
#
# Output: diagrams-loader.html (referenced from the qmd YAML
#         `include-after-body`).
#
# Rule: mermaid-dashboard-pattern

set -euo pipefail

SRC="${1:-diagrams.js}"
DST="${2:-${SRC%.js}-loader.html}"

if [ ! -f "$SRC" ]; then
  echo "error: source file '$SRC' not found" >&2
  exit 2
fi

{
  printf '<!-- Generated by inline-diagrams.sh from %s -->\n' "$SRC"
  printf '<!-- DO NOT EDIT THIS FILE — edit %s and re-run inline-diagrams.sh. -->\n' "$SRC"
  printf '<script type="module">\n'
  cat "$SRC"
  printf '\n</script>\n'
} > "$DST"

echo "wrote $DST ($(wc -l < "$DST") lines)"
